// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KdSoft.Lmdb.Tests.fbs
{

using global::System;
using global::FlatBuffers;

public struct LineItemKey : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LineItemKey GetRootAsLineItemKey(ByteBuffer _bb) { return GetRootAsLineItemKey(_bb, new LineItemKey()); }
  public static LineItemKey GetRootAsLineItemKey(ByteBuffer _bb, LineItemKey obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LineItemKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ProdCode { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetProdCodeBytes() { return __p.__vector_as_arraysegment(4); }
  public int OrderId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<LineItemKey> CreateLineItemKey(FlatBufferBuilder builder,
      StringOffset prodCodeOffset = default(StringOffset),
      int orderId = 0) {
    builder.StartObject(2);
    LineItemKey.AddOrderId(builder, orderId);
    LineItemKey.AddProdCode(builder, prodCodeOffset);
    return LineItemKey.EndLineItemKey(builder);
  }

  public static void StartLineItemKey(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddProdCode(FlatBufferBuilder builder, StringOffset prodCodeOffset) { builder.AddOffset(0, prodCodeOffset.Value, 0); }
  public static void AddOrderId(FlatBufferBuilder builder, int orderId) { builder.AddInt(1, orderId, 0); }
  public static Offset<LineItemKey> EndLineItemKey(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LineItemKey>(o);
  }
  public static void FinishLineItemKeyBuffer(FlatBufferBuilder builder, Offset<LineItemKey> offset) { builder.Finish(offset.Value); }
};


}
