// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KdSoft.Lmdb.Tests.fbs
{

using global::System;
using global::FlatBuffers;

public struct LineItem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LineItem GetRootAsLineItem(ByteBuffer _bb) { return GetRootAsLineItem(_bb, new LineItem()); }
  public static LineItem GetRootAsLineItem(ByteBuffer _bb, LineItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LineItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public LineItemKey? Key { get { int o = __p.__offset(4); return o != 0 ? (LineItemKey?)(new LineItemKey()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int Quantity { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<LineItem> CreateLineItem(FlatBufferBuilder builder,
      Offset<LineItemKey> keyOffset = default(Offset<LineItemKey>),
      int quantity = 0) {
    builder.StartObject(2);
    LineItem.AddQuantity(builder, quantity);
    LineItem.AddKey(builder, keyOffset);
    return LineItem.EndLineItem(builder);
  }

  public static void StartLineItem(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddKey(FlatBufferBuilder builder, Offset<LineItemKey> keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddQuantity(FlatBufferBuilder builder, int quantity) { builder.AddInt(1, quantity, 0); }
  public static Offset<LineItem> EndLineItem(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LineItem>(o);
  }
  public static void FinishLineItemBuffer(FlatBufferBuilder builder, Offset<LineItem> offset) { builder.Finish(offset.Value); }
};


}
